name: 'Dependency Track'

on: [pull_request]


env:
  SCAN_DEBUG_MODE: DEBUG

jobs:
  dependency-track:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install poetry
      - name: cyclonedx installer
        run: poetry add cyclonedx-bom
      - name: generate cyclonedx
        run: python3 -m cyclonedx_py -p
