name: 'Dependency Track'

on: [pull_request]


env:
  SCAN_DEBUG_MODE: DEBUG

jobs:
  dependency-track:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g @appthreat/cdxgen
      - name: Generate CycloneDX SBOM
        run: cdxgen . -o ./reports/bom.xml
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
