name: 'Dependency Track'

on: [pull_request]

jobs:
  dependency-track:
    runs-on: ubuntu-latest
    steps:
      - name: Generate CycloneDX SBOM
        uses: AppThreat/cdxgen-action@v1.0.0
        with:
          output: "./reports/bom.xml"
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
